# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # FluentD or Fluent Bit receiver
  fluentforward:
    endpoint: 0.0.0.0:8006

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['localhost:8888']
      - job_name: 'java-server-node-exporter'
        scrape_interval: 10s
        static_configs:
        - targets: ['10.111.1.236:9100']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    #endpoint: http://10.111.2.4:4317
    #tls:
      #insecure: true
  loki:
    endpoint: http://10.111.2.4:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true

  prometheusremotewrite:
    endpoint: "https://10.111.2.4:9090/api/v1/push"
    external_labels:
      system: otel_demo
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlp, logging]

    logs:
      receivers: [otlp, fluentforward]
      processors: [batch]
      exporters: [otlp, logging, loki]
  extensions: [health_check, pprof, zpages]
