# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['localhost:8888']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp:
    # endpoint: https://otlp.nr-data.net:4317
    # headers:
    #   api-key: ${NEW_RELIC_LICENSE_KEY}
    endpoint: http://localhost:4318

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlp, logging]

    logs:
      receivers: [otlp]
      processors: [batch]
        #exporters: [otlp, logging]
      exporters: [logging]
  extensions: [health_check, pprof, zpages]